before_install:
  - gem install cocoapods -v '1.0.0'

language: objective-c  #1
osx_image: xcode7.3 #2
xcode_workspace: socialCalendar.xcworkspace #3
xcode_scheme: socialCalendar #4
xcode_sdk: iphonesimulator9.3 #